### ISSUE TITLE
Potentially use lambda as top node for queries

### ISSUE THREAD

**Issue by masonproffitt** [iris-hep/qastle#1]
Using a `lambda` can avoid an externally defined name for the underlying data source, which is probably more portable. So it would be something like:
```lisp
(lambda (list data_source)
        (Select data_source
                ...))

**Comment by masonproffitt** [comment]
I think we've moved past this, since the data source is defined within the Python source/AST that generates the qastle text. As long as qastle can represent that data source definition in some way (e.g., via `Call` nodes), this wouldn't be any more general.

**Comment by gordonwatts** [comment]
Yeah - I used to have new AST nodes to represent this, but after `qastle` couldn't deal with those, I turned them into `call` ast nodes.
