### ISSUE TITLE
This needs to be installed in pypi

### ISSUE THREAD

**Issue by gordonwatts** [iris-hep/qastle#18]
So we can just do the install from pip.

Before this happens a better name than "ast-language" needs to become up with - this is too generic.

**Comment by masonproffitt** [comment]
Putting it on PyPI is easy enough. As for the name, the package really is quite generic, so I couldn't think of anything better at the time. I guess putting "query" in there somewhere could be more descriptive. Do you have a suggestion?

**Comment by masonproffitt** [comment]
My attempt at a name: Query AST Language Expressions -> qastle (like "castle")

**Comment by gordonwatts** [comment]
I would say that was awesome!

**Comment by masonproffitt** [comment]
Done (https://pypi.org/project/qastle/).
